services:
  torproxy:
    image: dperson/torproxy
    ports:
      - 9050:9050
    networks:
        - tor
  clicker:
    environment:
      - HTTP_PROXY=socks5://torproxy:9050
      - HTTPS_PROXY=socks5://torproxy:9050
    build: 
      context: .
      dockerfile: ./docker/clicker/Dockerfile
    depends_on:
      torproxy:
        condition: service_healthy
    networks:
      - tor

networks:
  tor:
    driver: bridge